// Base de datos oficial basada en el Taller de Cata y la Rueda Aromaster (88 aromas)
const CASOS_ENOLOGIA = [
    {
        id: 1,
        titulo: "Cabernet Sauvignon Reserva",
        percepcion: "Copa en reposo - Vía Nasal Directa",
        descripcion: "Al acercar la nariz a la copa sin agitar, se percibe claramente un aroma vegetal punzante e intenso que recuerda a la huerta fresca.",
        macroCorrecta: "Aroma (Primario/Secundario)",
        familiaCorrecta: "Vegetal",
        descriptorCorrecto: "pimiento",
        explicacion: "Las pirazinas son compuestos aromáticos primarios que provienen de la uva. Son muy volátiles y características del Cabernet Sauvignon y Cabernet Franc.",
        distractoresMacro: ["Bouquet (Terciario)", "Defecto"],
        distractoresFamilia: ["Frutas Rojas", "Tostado", "Flores Blancas"],
        distractoresDescriptor: ["tomate", "hinojo", "eucalipto"]
    },
    {
        id: 2,
        titulo: "Chardonnay Crianza en Barrica",
        percepcion: "Copa agitada - Vía Nasal Directa",
        descripcion: "Tras hacer girar el vino en la copa para liberar moléculas menos volátiles, aparecen notas dulces que recuerdan a la repostería fina.",
        macroCorrecta: "Bouquet (Terciario)",
        familiaCorrecta: "Tostado",
        descriptorCorrecto: "vainilla",
        explicacion: "El contacto del vino con el roble durante la crianza aporta vanillina derivada de la degradación térmica de la lignina de la madera.",
        distractoresMacro: ["Aroma (Primario/Secundario)", "Defecto"],
        distractoresFamilia: ["Cítricos", "Hierbas Frescas", "Sulfitos"],
        distractoresDescriptor: ["caramelo", "chocolate", "pan"]
    },
    {
        id: 3,
        titulo: "Chardonnay con Fermentación Maloláctica",
        percepcion: "Vía Retronasal (En boca)",
        descripcion: "Al calentar el vino en la cavidad bucal, la vía retronasal detecta un aroma untuoso que recuerda a productos lácteos frescos.",
        macroCorrecta: "Aroma (Primario/Secundario)",
        familiaCorrecta: "Malo-Láctica / Levaduras",
        descriptorCorrecto: "mantequilla",
        explicacion: "El diacetilo es un compuesto secundario generado por las bacterias lácticas durante la fermentación maloláctica.",
        distractoresMacro: ["Bouquet (Terciario)", "Defecto"],
        distractoresFamilia: ["Frutas de Hueso", "Maderas", "Animal"],
        distractoresDescriptor: ["pan", "queroseno", "miel"]
    },
    {
        id: 4,
        titulo: "Torrontés Riojano Joven",
        percepcion: "Primera Olfación",
        descripcion: "Inhalación corta que revela una fragancia floral delicada y dulce, muy elegante en copa limpia.",
        macroCorrecta: "Aroma (Primario/Secundario)",
        familiaCorrecta: "Flores Blancas",
        descriptorCorrecto: "jazmín",
        explicacion: "Los terpénicos son terpenos aromáticos primarios presentes en el hollejo de la uva de variedades terpénicas como Torrontés o Moscatel.",
        distractoresMacro: ["Bouquet (Terciario)", "Defecto"],
        distractoresFamilia: ["Nueces", "Especias", "Oxidado"],
        distractoresDescriptor: ["rosa", "lavanda", "acacia"]
    },
    {
        id: 5,
        titulo: "Malbec Gran Reserva (Estiba en Botella)",
        percepcion: "Evolución en Copa",
        descripcion: "En un tinto con más de 4 años de guarda, aparece una nota compleja, profunda y de carácter animal.",
        macroCorrecta: "Bouquet (Terciario)",
        familiaCorrecta: "Animal",
        descriptorCorrecto: "cuero",
        explicacion: "Los aromas terciarios de la serie animal surgen durante la fase reductora de la estiba en botella por evolución de los polifenoles.",
        distractoresMacro: ["Aroma (Primario/Secundario)", "Defecto"],
        distractoresFamilia: ["Frutas Tropicales", "Verduras", "Cítricos"],
        distractoresDescriptor: ["trufa", "salsa de carne", "matorral"]
    },
    {
        id: 6,
        titulo: "Muestra de Tanque de Inox (Anomalía)",
        percepcion: "Primera Olfación Directa",
        descripcion: "Aroma extremadamente volátil y punzante que recuerda a remedio de cocina o aderezo de ensalada.",
        macroCorrecta: "Defecto",
        familiaCorrecta: "Acidez Volátil",
        descriptorCorrecto: "vinagre",
        explicacion: "Producido por bacterias acéticas (Acetobacter) que transforman el etanol en ácido acético al tener contacto no deseado con oxígeno.",
        distractoresMacro: ["Aroma (Primario/Secundario)", "Bouquet (Terciario)"],
        distractoresFamilia: ["Maderas", "Frutas Rojas", "Tostado"],
        distractoresDescriptor: ["disolv. de tinta de uñas", "cebolla", "caucho"]
    },
    {
        id: 7,
        titulo: "Sauvignon Blanc de Zona Fría",
        percepcion: "Copa en Reposo",
        descripcion: "Aroma cítrico punzante y fresco con perfil refrescante y ligeramente ácido.",
        macroCorrecta: "Aroma (Primario/Secundario)",
        familiaCorrecta: "Cítricos",
        descriptorCorrecto: "pomelo",
        explicacion: "Los tioles varietales aportan estas notas cítricas frescas en climas fríos o cosechas tempranas de Sauvignon Blanc.",
        distractoresMacro: ["Bouquet (Terciario)", "Defecto"],
        distractoresFamilia: ["Frutas Botritizadas", "Especias", "Nueces"],
        distractoresDescriptor: ["limón", "lima", "grosella espinosa"]
    },
    {
        id: 8,
        titulo: "Syrah Criado en Roble Americano",
        percepcion: "Copa Agitada",
        descripcion: "Sensación aromática cálida y especiada que resalta al agitar el vino.",
        macroCorrecta: "Bouquet (Terciario)",
        familiaCorrecta: "Especias",
        descriptorCorrecto: "pimienta",
        explicacion: "La presencia del compuesto rotundona en la uva sumado a la crianza en roble intensifica el perfil especiado.",
        distractoresMacro: ["Aroma (Primario/Secundario)", "Defecto"],
        distractoresFamilia: ["Hierbas Secas", "Lácticos", "Brett"],
        distractoresDescriptor: ["canela", "nuez moscada", "clavel"]
    },
    {
        id: 9,
        titulo: "Muestra con Contaminación de Tapón",
        percepcion: "Reposado en Copa",
        descripcion: "El vino ha perdido todo su perfil frutal y despide un olor húmedo similar a humedad o humedad de bodega vieja.",
        macroCorrecta: "Defecto",
        familiaCorrecta: "Enfermedad Corcho",
        descriptorCorrecto: "sabor al corcho",
        explicacion: "Causado por la presencia de 2,4,6-tricloroanisol (TCA), compuesto que enmascara los aromas primarios del vino.",
        distractoresMacro: ["Aroma (Primario/Secundario)", "Bouquet (Terciario)"],
        distractoresFamilia: ["Matorral", "Maderas", "Mineral"],
        distractoresDescriptor: ["trufa", "musgo de árbol", "madera"]
    },
    {
        id: 10,
        titulo: "Merlot / Malbec Blend de Roble Tostado Intenso",
        percepcion: "Persistencia Aromática",
        descripcion: "Aroma profundo y tostado que recuerda a la infusión matutina o granos tostados.",
        macroCorrecta: "Bouquet (Terciario)",
        familiaCorrecta: "Tostado",
        descriptorCorrecto: "café",
        explicacion: "Derivado del tostado fuerte o intenso de las duelas de las barricas de roble durante su fabricación.",
        distractoresMacro: ["Aroma (Primario/Secundario)", "Defecto"],
        distractoresFamilia: ["Bayas Rojas", "Flores de Colores", "Mineral"],
        distractoresDescriptor: ["chocolate", "caramelo", "humo"]
    }
];
